name: Sync to Gitee

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      # 2. 配置Git用户信息
      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
      # 3. 添加Gitee远程仓库(使用HTTPS+令牌认证)
      - name: Add Gitee Remote
        run: |
          git remote add gitee https://${{ secrets.GITEE_USERNAME }}:${{ secrets.GITEE_ACCESS_TOKEN }}@gitee.com/${{ secrets.GITEE_USERNAME }}/AzurLaneAutoScript.git
          
      # 4. 强制推送到Gitee
      - name: Push to Gitee
        run: |
          git push gitee HEAD:main --force
